import { createSlice } from "@reduxjs/toolkit";
const initialState = {
  blogs: [
    {
      id: 1,
      title: "Why Walmart is trouncing Amazon in the grocery wars",
      dec: "Have realistic expectations When amazon announced the $13.7bn acquisition of Whole Foods Market",
      categories: "Blog",
      img: "https://coaching.thimpress.com/healthy-coaching/wp-content/uploads/sites/49/2023/06/blog-5.png",
      author: "Michael",
    },
    {
      id: 2,
      title: "Banking startup started Elon Musk’s passion for the letter X",
      dec: "Elon Musk has been pushing the X brand since before the turn of the century, starting with online banking",
      categories: "Blog",
      img: "https://coaching.thimpress.com/healthy-coaching/wp-content/uploads/sites/49/2023/06/blog-6.png",
      author: "Michael",
    },
    {
      id: 3,
      title:
        "Expert advice: Should you spend 25% of your income on investing in stocks?",
      dec: "In an interview with ETMarkets, Bhave, who has over 25 years of experience across the financial",
      categories: "Blog",
      img: "https://coaching.thimpress.com/healthy-coaching/wp-content/uploads/sites/49/2023/06/blog-7.png",
      author: "Michael",
    },
    {
      id: 4,
      title: "Savings interest rate is less than 8% a year",
      dec: "Depending on the account balance, savings account interest rates will vary. Here are banks offering saving",
      categories: "Blog",
      img: "https://coaching.thimpress.com/healthy-coaching/wp-content/uploads/sites/49/2023/06/blog-8.png",
      author: "Michael",
    },
    {
      id: 5,
      title: "Human resource development strategy",
      dec: "The human resources department of a company must be well versed in current management trends, and sta",
      categories: "Blog",
      img: "https://coaching.thimpress.com/healthy-coaching/wp-content/uploads/sites/49/2023/06/blog-10.png",
      author: "Michael",
    },
    {
      id: 6,
      title: "Next-generation Googles run a tighter ship",
      dec: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry",
      categories: "Blog",
      img: "https://coaching.thimpress.com/healthy-coaching/wp-content/uploads/sites/49/2023/06/blog-9.png",
      author: "Michael",
    },
    {
      id: 7,
      title: "Tesla’s surprising new route to EV domination",
      dec: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tempus nibh sed maximus",
      categories: "Video",
      img: "https://coaching.thimpress.com/healthy-coaching/wp-content/uploads/sites/49/2023/06/blog-11.png",
      author: "Michael",
    },
    {
      id: 8,
      title: "A battle of rickshaw apps shows the promise of India’s",
      dec: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tempus nibh sed maximus",
      categories: "Video",
      img: "https://coaching.thimpress.com/healthy-coaching/wp-content/uploads/sites/49/2023/06/blog-12.png",
      author: "Michael",
    },
    {
      id: 9,
      title: "McDonald’s is about to report earnings",
      dec: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tempus nibh sed maximus",
      categories: "Video",
      img: "https://coaching.thimpress.com/healthy-coaching/wp-content/uploads/sites/49/2023/06/blog-13.png",
      author: "Michael",
    },
    {
      id: 10,
      title: "Episode 5",
      dec: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tempus nibh sed maximus",
      categories: "Podcast",
      img: "https://coaching.thimpress.com/healthy-coaching/wp-content/uploads/sites/49/2023/06/blog-8.png",
      author: "Michael",
    },
    {
      id: 11,
      title: "Episode 4",
      dec: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tempus nibh sed maximus",
      categories: "Podcast",
      img: "https://coaching.thimpress.com/healthy-coaching/wp-content/uploads/sites/49/2023/06/blog-13.png",
      author: "Michael",
    },
    {
      id: 12,
      title: "Episode 4",
      dec: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tempus nibh sed maximus",
      categories: "Podcast",
      img: "https://coaching.thimpress.com/healthy-coaching/wp-content/uploads/sites/49/2023/06/blog-13.png",
      author: "Michael",
    },
    {
      id: 13,
      title: "Episode 3",
      dec: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tempus nibh sed maximus",
      categories: "Podcast",
      img: "https://coaching.thimpress.com/healthy-coaching/wp-content/uploads/sites/49/2023/06/blog-11.png",
      author: "Michael",
    },
    {
      id: 14,
      title: "Episode 2",
      dec: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
      categories: "Podcast",
      img: "https://coaching.thimpress.com/healthy-coaching/wp-content/uploads/sites/49/2023/06/blog-10.png",
      author: "Michael",
    },
    {
      id: 15,
      title: "Episode 1",
      dec: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tempus nibh sed maximus",
      categories: "Podcast",
      img: "https://coaching.thimpress.com/healthy-coaching/wp-content/uploads/sites/49/2023/06/blog-6.png",
      author: "Michael",
    },
    {
      id: 16,
      title: "Coca-Cola says it’s done raising prices in the U.S. and",
      dec: "For has been raising prices on its drinks to combat higher costs. But the company said Wednesday it’s done",
      categories: "Blog",
      img: "https://coaching.thimpress.com/healthy-coaching/wp-content/uploads/sites/49/2022/05/blog-14.png",
      author: "Michael",
    },
    {
      id: 17,
      title: "Franchising industry holds its breath as FTC takes a",
      dec: "Last month, the Federal Trade Commission wrapped up a public comment period in response to its",
      categories: "Blog",
      img: "https://coaching.thimpress.com/healthy-coaching/wp-content/uploads/sites/49/2022/05/blog-15.png",
      author: "Michael",
    },
    {
      id: 18,
      title: "Main Street’s labor problem is weighing on businesses as",
      dec: "As summer arrives, Alison Schuch, owner of Fells Point Surf Co., is down about 10 workers at her two beach",
      categories: "Blog",
      img: "https://coaching.thimpress.com/healthy-coaching/wp-content/uploads/sites/49/2023/06/blog-6.png",
      author: "Michael",
    },
    {
      id: 19,
      title: "IRS weighing guidance for small business tax credit,",
      dec: "After a flood of business returns with a pandemic-era tax credit, the IRS is weighing guidance for those who",
      categories: "Blog",
      img: "https://coaching.thimpress.com/healthy-coaching/wp-content/uploads/sites/49/2023/06/blog-13.png",
      author: "Michael",
    },
    {
      id: 20,
      title: "How to keep your business deposit cash safe during a",
      dec: "After a flood of business returns with a pandemic-era tax credit, the IRS is weighing guidance for those who",
      categories: "Blog",
      img: "https://coaching.thimpress.com/healthy-coaching/wp-content/uploads/sites/49/2022/05/blog-15.png",
      author: "Michael",
    },
    {
      id: 21,
      title: "The biggest mistakes owners make when selling their",
      dec: "After a flood of business returns with a pandemic-era tax credit, the IRS is weighing guidance for those who",
      categories: "Design - Branding",
      img: "https://coaching.thimpress.com/healthy-coaching/wp-content/uploads/sites/49/2023/06/blog-6.png",
      author: "Michael",
    },
    {
      id: 22,
      title: "Inflation? Recession? Starting Black Friday,",
      dec: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry",
      categories: "Business",
      img: "https://coaching.thimpress.com/healthy-coaching/wp-content/uploads/sites/49/2023/06/blog-8.png",
      author: "Michael",
    },
    {
      id: 23,
      title: "Why Mark Zuckerberg is talking so much about",
      dec: "WhatsApp is already widely popular with U.S. consumers. Now Meta turning more attention to building its",
      categories: "Business",
      img: "https://coaching.thimpress.com/healthy-coaching/wp-content/uploads/sites/49/2023/06/blog-7.png",
      author: "Michael",
    },
    {
      id: 24,
      title: "What the pro-business tax agenda is chasing in a",
      dec: "It is a long established fact that a reader will be distracted by the readable content of a page when.",
      categories: "Business",
      img: "https://coaching.thimpress.com/healthy-coaching/wp-content/uploads/sites/49/2023/06/blog-5.png",
      author: "Blog",
    },
    {
      id: 25,
      title: "How to Prevent Your Emotional Insecurity",
      dec: "It is a long established fact that a reader will be distracted by the readable content of a page when...",
      categories: "Business",
      img: "https://coaching.thimpress.com/healthy-coaching/wp-content/uploads/sites/49/2016/01/blog-5.jpg",
      author: "Blog",
    },
  ],
};

export const blogSlice = createSlice({
  name: "blogs",
  initialState,
  reducers: {},
});

export const {} = blogSlice.actions;
export default blogSlice.reducer;
